# Generated by Django 4.1.7 on 2024-04-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownTime',
            new_name='customers',
        ),
    ]
