# Generated by Django 4.1.7 on 2024-04-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0002_rename_downtime_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=255)),
                ('CustomerID', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='customers',
        ),
    ]
