# Generated by Django 4.1.7 on 2024-04-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0003_customer_delete_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ActiveCustomer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
