# Generated by Django 4.1.7 on 2024-04-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0004_customer_activecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
