# Generated by Django 4.1.7 on 2024-04-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0005_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosDeFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodDef', models.CharField(max_length=6)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=6)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdTecnico', models.IntegerField()),
                ('FechaPrueba', models.DateTimeField()),
                ('FechaDiagnostico', models.DateTimeField()),
                ('idCliente', models.IntegerField()),
                ('idModelo', models.IntegerField()),
                ('Revision', models.CharField(max_length=255)),
                ('NoSerie', models.CharField(max_length=255)),
                ('Prueba', models.CharField(max_length=6)),
                ('DescPrueba', models.CharField(max_length=255)),
                ('idDefecto', models.IntegerField()),
                ('Responsable', models.CharField(max_length=255)),
                ('idAccion', models.IntegerField()),
                ('Referencia', models.CharField(max_length=255)),
                ('Tiempo', models.IntegerField()),
                ('Status', models.CharField(max_length=255)),
                ('Comentario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroControl', models.CharField(max_length=255)),
                ('IdPropietario', models.IntegerField()),
                ('IdModelo', models.IntegerField()),
                ('TipoEquipo', models.IntegerField()),
                ('Active', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial', models.CharField(max_length=255)),
                ('FechaEntrada', models.DateTimeField()),
                ('FechaSalida', models.DateTimeField()),
                ('Estatus', models.CharField(max_length=255)),
                ('Modelo', models.CharField(max_length=255)),
                ('Revision', models.CharField(max_length=255)),
                ('Cliente', models.CharField(max_length=255)),
                ('SigEstacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LastManto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEquipo', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('IdManto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEquipo', models.IntegerField()),
                ('MantoDate', models.DateTimeField()),
                ('MantoNextDate', models.DateTimeField()),
                ('IdTechnician', models.IntegerField()),
                ('Comments', models.CharField(max_length=255)),
                ('IdMantoFile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MantoRegisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUser', models.IntegerField()),
                ('NombreReporte', models.CharField(max_length=255)),
                ('Date', models.DateTimeField()),
                ('NextDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCliente', models.IntegerField()),
                ('Modelo', models.CharField(max_length=255)),
                ('ActiveModel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PCEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEquipo', models.IntegerField()),
                ('PCName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiemposMuertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField()),
                ('IdEquipo', models.IntegerField()),
                ('Turno', models.IntegerField()),
                ('IdIniciador', models.IntegerField()),
                ('IdTecnico', models.IntegerField()),
                ('Falla', models.CharField(max_length=255)),
                ('HoraInicio', models.DateTimeField()),
                ('HoraTermino', models.DateTimeField()),
                ('IdEnsamble', models.IntegerField()),
                ('Causa', models.CharField(max_length=255)),
                ('Solucion', models.CharField(max_length=255)),
                ('HoraTecnico', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNumber', models.IntegerField()),
                ('employeeName', models.CharField(max_length=255)),
            ],
        ),
    ]
