# Generated by Django 4.1.7 on 2024-05-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0006_codigosdefalla_defecto_diagnostico_equipo_inventario_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='user',
            name='create',
            field=models.BooleanField(default=False),
        ),
    ]
