# Generated by Django 4.1 on 2024-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0007_rename_solucion_tiemposmuertos_accion_user_create'),
    ]

    operations = [
        
        
        migrations.AlterField(
            model_name='modelo',
            name='ActiveModel',
            field=models.IntegerField(default=True),
        ),
    ]
