# Generated by Django 4.1 on 2024-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0008_goldenpcba_rename_solucion_tiemposmuertos_accion_and_more'),
    ]

    operations = [
        
        
        
    ]
