# Generated by Django 4.1 on 2024-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0009_remove_tiemposmuertos_solucion_goldenpcba_birthfile_and_more'),
    ]

    
