# Generated by Django 4.1 on 2024-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDT', '0010_alter_tiemposmuertos_accion'),
    ]

    operations = [
        
        
    ]
